build:
  nodes:
    analysis:
      dependencies:
        after:
          - composer require --dev "squizlabs/php_codesniffer=3.7.2"

      tests:
        override:
          - command: phpcs-run ./
            use_website_config: false
